"""initial_schema

Revision ID: c0cf53fababe
Revises: 
Create Date: 2026-08-24 12:27:45.031948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cf53fababe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('video_style', sa.String(length=100), nullable=True),
    sa.Column('image_style', sa.String(length=100), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('background_music', sa.Boolean(), nullable=False),
    sa.Column('subtitles_enabled', sa.Boolean(), nullable=False),
    sa.Column('generation_mode', sa.Enum('FULLY_AUTOMATIC', 'REVIEW_SCRIPT', 'REVIEW_ASSETS', 'REVIEW_BEFORE_FINAL', name='generationmode'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PROCESSING', 'AWAITING_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('script_data', sa.JSON(), nullable=True),
    sa.Column('visual_style_data', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('final_video_url', sa.String(length=500), nullable=True),
    sa.Column('narration_url', sa.String(length=500), nullable=True),
    sa.Column('subtitle_url', sa.String(length=500), nullable=True),
    sa.Column('narration_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.Enum('SCRIPT_GENERATION', 'SCENE_PROMPT_GENERATION', 'FLOW_IMAGE_GENERATION', 'FLOW_VIDEO_GENERATION', 'ELEVENLABS_GENERATION', 'VIDEO_COMPOSITION', 'FINALIZATION', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_scene_id'), 'jobs', ['scene_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('video_prompt', sa.Text(), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'FLOW_AUTOMATION_ERROR', 'RETRYING', name='scenestatus'), nullable=False),
    sa.Column('image_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'FLOW_AUTOMATION_ERROR', 'RETRYING', name='scenestatus'), nullable=False),
    sa.Column('video_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'FLOW_AUTOMATION_ERROR', 'RETRYING', name='scenestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_index(op.f('ix_scenes_status'), 'scenes', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'SUBTITLE', 'FINAL_VIDEO', 'ERROR_SCREENSHOT', name='assettype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'CORRUPTED', name='assetstatus'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_scene_id'), 'assets', ['scene_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_scene_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_scenes_status'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scene_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
